//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package test

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewTestBuilder() *TestBuilder {
	builder := &TestBuilder{}
	builder.model = Test{}
	builder.testa = NewTestABuilder()
	builder.testblist = []*TestBBuilder{}
	builder.testblistpointer = []*TestBBuilder{}
	builder.testbalias = []*TestBBuilder{}
	return builder
}

type TestBuilder struct {
	model            Test
	testa            *TestABuilder
	testb            *TestBBuilder
	testblist        []*TestBBuilder
	testblistpointer []*TestBBuilder
	testbalias       []*TestBBuilder
}

func (b *TestBuilder) Key(input string) {
	b.model.Key = input
}

func (b *TestBuilder) Tas(input int) {
	b.model.Tas = input
}

func (b *TestBuilder) TestA() *TestABuilder {
	return b.testa
}

func (b *TestBuilder) TestB() *TestBBuilder {
	if b.testb == nil {
		b.testb = NewTestBBuilder()
	}
	return b.testb
}

func (b *TestBuilder) AddTestBList() *TestBBuilder {
	builder := NewTestBBuilder()
	b.testblist = append(b.testblist, builder)
	return builder
}

func (b *TestBuilder) AddTestBListPointer() *TestBBuilder {
	builder := NewTestBBuilder()
	b.testblistpointer = append(b.testblistpointer, builder)
	return builder
}

func (b *TestBuilder) AddTestBAlias() *TestBBuilder {
	builder := NewTestBBuilder()
	b.testbalias = append(b.testbalias, builder)
	return builder
}

func (b *TestBuilder) Build() Test {
	b.model.TestA = b.testa.Build()
	if b.testb != nil {
		testb := b.testb.Build()
		b.model.TestB = &testb
	}
	b.model.TestBList = []TestB{}
	for _, v := range b.testblist {
		b.model.TestBList = append(b.model.TestBList, v.Build())
	}
	b.model.TestBListPointer = []*TestB{}
	for _, v := range b.testblistpointer {
		vv := v.Build()
		b.model.TestBListPointer = append(b.model.TestBListPointer, &vv)
	}
	b.model.TestBAlias = []*TestB{}
	for _, v := range b.testbalias {
		vv := v.Build()
		b.model.TestBAlias = append(b.model.TestBAlias, &vv)
	}
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewTestABuilder() *TestABuilder {
	builder := &TestABuilder{}
	builder.model = TestA{}
	builder.testb = NewTestBBuilder()
	return builder
}

type TestABuilder struct {
	model TestA
	testb *TestBBuilder
}

func (b *TestABuilder) TestB() *TestBBuilder {
	return b.testb
}

func (b *TestABuilder) Build() TestA {
	b.model.TestB = b.testb.Build()
	return b.model
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func NewTestBBuilder() *TestBBuilder {
	builder := &TestBBuilder{}
	builder.model = TestB{}
	return builder
}

type TestBBuilder struct {
	model TestB
}

func (b *TestBBuilder) TestBKey(input string) {
	b.model.TestBKey = input
}

func (b *TestBBuilder) Build() TestB {
	return b.model
}
